{% set name = "pdfminer" %}
{% set version = "20140328" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: ba187b93056586a14edd5e630cf63ae96b1cc84b611f55dcddbc997316d9f262

build:
  skip: True  # [py3k]
  number: 1000
  script: python setup.py install

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - pdfminer

about:
  home: http://euske.github.io/pdfminer/index.html
  license: MIT
  summary: 'PDF parser and analyzer'

extra:
  recipe-maintainers:
    - pmlandwehr
