# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "dK3QopwwRVCkCx64gaa+zxX8R6/MLfbnT3ct3ks/GPjcJmVeYR0ndE8Ngqtv3tW6+OEQFnxSMu5VTBQJQXjJzMsX3i1oitGX8PzxAie9d7if7NqvLPuNxVDLRS8y7e55fWz+lo9exwk3wKVcz4oOAdg4xPmGtB8xmezsuS1kjkEolE1Ep1Ztx5uIByuKEv6GrtvhZ/CY7TWpsYmQw3wANZUjF+Jate6TDw/G7T8A6B+0DUtA6wIB1bIOa1/apyaHT5cgy6VwN/aB6TjsVCVorvcNXerynpq38+Tz1LAUts/Zr1iHqbC1orVk6xmNvgO1IKQb+2c9mp/eriM4CrPwP5TK41Ut+AlOPK/k4ZdDpTjdMAaNek/ALTd5G692069TSKAGXSXbKrdkzTGiLogY/16FFS6Q7PqT1sx4gMtwB08WvGqOX/xQPog9IlOU0qNM/1lkKMInEEd/2n+Df6Nq+yuu8IkwaJdL6ufFeO48/YN4mOUqy582ReNBRsLAIVQh2zhmrKQUvwS75vdft/oi2CopiSzcBXR/Zc1crhoX537dGvCG+EfhY6Nx09PuJMW2s1rtpxSiMldZR2WmVGk8qqRBgP+Up74+oJsbCjn5ndv3KGrUZLxksmfprQEn+0CMH74LNVdLzVyerabY+RJXu2Dfh+3ahGeC2B8weYtkGWI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
