travis:
  secure:
    BINSTAR_TOKEN: faZKCng90lY/EGH1FlrMrcpkghV09D9Xn0iG51txlvnhp3VdpjbG2EEf+XgWa8sRP9dAILQ3YaOQVp5IipVtLQfqfastA8YpKnZcGduCvPFwqFssvxLyHYlb2pLqeoYE8o+nJy9x7W0iHUQhLoc0e4CdS/uEyFSCHigWqqntTU9Wd/07SEyR77HZb6wFlDjV5dsIviw5IJGUjWhQrmp8myh4dlGCtr9pI+y7EXl/4IRxNSUkg18PO8TCrL8gzg4ljKkOn9jNpwqNHIIx7hy3lrSYEprvazuE4xgKMhhCK/rAio5Z/lGbQpE+1gPCC7dPaocLITpP71g98h4i3TjYXciO9CT17drr/N6tpI/2r+i2w8wtfg5Us1NjVRLVkjXJSvTqnKrevVEHmsUSPqilRXY6TVrpWVXp6J/U38QdNDzSMvkKbTZNQVBCaNfQeiYM/XquiI8qNE+yTXufo5L4hA63XzabaUgjJ5oDe72+5Hq7QUh6IUM/gSu1rIt/Omj3qH22CyDgrOl2M83qbPbZQNd3VketuBUz8V6O01g3K2AKnkUlWkl6Pt9F0El9UrnZEkLyaZLpiUv7k8WgA3jK73E7D+N4Stf26BMb3ZL/wa1gXm/nsrQM5xc7UjU38YS7+JhSAGwyB+n1ZmA8RYI1HGpLhnSuECpjqB60NYMBCnk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
