travis:
  secure:
    BINSTAR_TOKEN: ByMRnu6Gbo0GxuKrDmxY4nqosnoDW5F4cfWOt68qe1EFGTzRTq3Zu25btrO1MWQzTtRQvYQF+vhqPIWV3kkfhIuURE8seE6wy60LIr8+GkPBfnC9NifXNwgPtP11q1WWJonehLgBkKx6w/YBTAwwZNkcrCP4dLpR1j9oXPLS+Wa7Gmpg+hGUFR+9fpG8OEOVLdDxkxVhWfG4PeHuh12aMdBmj32uw2az6x8QdHrypTfh9CLdmb2vEcUJxCJI5GeV1nKuq8epSf3qgHrLdbCY17B1iLeQsXK8mCxqh0nee5M5agsumrcpxkat6yDebJWPUP+SmUZ53p5iceUL7XB4glRHWpQ80Jy8QfMIswzXoR47H9M/xGeMlKKG0BxCySo2VDEhgyX0ySJbRYKBsrgeOhMEK/9YoWCEM0wXzWxf3ZWg3eTUgk7g6SvXHy4yrgeUA6PGKKR1FkvzrqHlHQ+cZW2iAEKpnqGjCyqSxIKvb4Ogv7ZxNRGpGg6BhpE8ufCOXI5ABYZxqhQ2piJMhPd+m3QasJLyvGzLzCp2NMd2orH767oSjyZI7bx/mvw0yaki2ngIWAoXPFt+7cNCyCxK8EXj64abzxfASQVEChhvWJRuHs19PE1wMsGRhNgcxX5ItJzqb6fti+q39dz61LxlB9sfzwiBUEETF6xyFFJ+XKY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
